{
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/Notif_Create/Actions/Service/CreateOpenServiceFailureMessage.action",
	"OnSuccess": "/Notif_Create/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"Service": "/Notif_Create/Services/MicroService.service",
	"_Type": "Action.Type.ODataService.Open"
}