{
	"Service": "/Notif_Create/Services/Notification_Create.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/Notif_Create/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/Notif_Create/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}