{
	"Properties": {
		"Equipment": "#Control:FCEquipment/#Value",
		"FunctionalLocation": "#Control:FCFunctionalLocation/#Value",
		"ShortText": "#Control:FCShortText/#Value"
	},
	"Target": {
		"EntitySet": "PMNOTIFSet",
		"Service": "/Notif_Create/Services/Notification_Create.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}